### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by CJHFUTURE** [keijiro/Reaktion#10]
Hi is there any documentation or tutorial on how to implement this?

**Comment by keijiro** [comment]
I stopped working on this project two years ago, and now I'm using a new toolkit called Klak instead.

https://github.com/keijiro/Klak

So there is no plan for adding documentation/tutorials.

**Comment by CJHFUTURE** [comment]
That's cool.Does klack have implementation for controling  with sound?
