### ISSUE TITLE
Connecting an audio file in gears example scene

### ISSUE THREAD

**Issue by corbinyo** [keijiro/Reaktion#12]
Hi there, 

I am wondering if there is a way to connect an audio file to the gears example scene? Is there an Injector script to do such a thing?

Thank you.

**Comment by keijiro** [comment]
I've abandoned this project (Reaktion) and now working on a project with a similar concept.

https://github.com/keijiro/Klak

Also I've developed a native plugin for low-latency audio input. This is much more stable than the previous solutions.

https://github.com/keijiro/KlakLasp

So, I recommend using Klak instead of Reaktion.

**Comment by corbinyo** [comment]
Thank you so much!

I look forward to experimenting with these. I am in the early stages of building audio reactive visuals for a musical artist.

Much appreciated and I will make sure to keep you posted to my progress.

Thank you again,

Corbin

www.corbinordel.com

**Comment by corbinyo** [comment]
Hi Keijiro,

Is it possible in, for example the Particles example from the KlakLask-master folder, to have a audio file as the Audio Input as opposed to the microphone doing handling the audio?

Thank you for any and all help,

Corbin Ordel
www.corbinordel.com

**Comment by keijiro** [comment]
Try LASP Loopback branch.

https://github.com/keijiro/Lasp/tree/loopback

**Comment by corbinyo** [comment]
Sorry to ask again, but I am wondering if there has been a way found to use audio as an input without having to use loopback
www.corbinordel.com

**Comment by keijiro** [comment]
If you don't like to use the loopback plugin, try a virtual audio driver to feedback audio signals.

https://www.google.com/search?q=virtual+audio+driver

**Comment by corbinyo** [comment]
Thank you for your help once again - I decided I would make sure to learn how to do this, So I am here to ask if I can use Lasp-Loopback with Reaktion. I have made it this far but am unable to connect my "
![lasp-loopback](https://user-images.githubusercontent.com/14141336/34514774-f7622ef2-f03c-11e7-992f-2299636674bd.png)
Reaktor Source" with the loopback "effect"

**Comment by keijiro** [comment]
No. Lasp isn't supported with Reaktion. You have to write a custom script to support it.
