### ISSUE TITLE
Request: Need a basic 'how to' document on implementation in a scene

### ISSUE THREAD

**Issue by viknesh2020** [keijiro/Reaktion#14]
Hi Keijiro.. you have done a fabulous work ! But please put a simple know how document for implementation in any scene in Unity. Thanks !

**Comment by keijiro** [comment]
Unfortunately, I abandoned this project several years ago. Sorry for not being helpful, but I won't invest time on this project.

I'm closing this issue now. Please feel free to reopen for further questions.
