### ISSUE TITLE
All sample scenes is not working on Unity 5

### ISSUE THREAD

**Issue by kidapu** [keijiro/Reaktion#5]
Unity5でこのレポジトリのサンプルのシーンを動かそうとすると、すべてのシーンで「The referenced script on this Behaviour is missing」というwarningが出て、動きません。原因がわかったら嬉しいです。よろしくお願い致します。

**Comment by fagopyrum** [comment]
same problem here.

**Comment by keijiro** [comment]
Fixed!

**Comment by lejeanf** [comment]
does not seem so.

Using unity 5.6.1f1 & windows 10
